### ISSUE TITLE
Strange colors (Set PCB from 16 bit to 8 bit)

### ISSUE THREAD

**Issue by shaddow501** [iwalpola/Adafruit_ILI9341_8bit_STM#1]
Hello,

I try to work with your lib and tested on 2 tft ili9341 screens and I have the same error.
the display  show only the blue color and when I change in the code to show in other color it still show blue...

What could be the problem? the wiring are correct (tested over and over that connections are made to the correct pin outs.

**Comment by iwalpola** [comment]
Hi can you show a picture? Is it updating the screen at all?
What does the serial output show?

**Comment by iwalpola** [comment]
Library usually works with ILI9341: https://www.youtube.com/watch?v=RKkBmD_i6sk

**Comment by shaddow501** [comment]
The ili9341 works with only blue color since it is connected only as 8 bit and not 16.
How do I change the controller to work as 8 bit and not 16?

Ilan B. (Mobile)

-----Original Message-----

**Comment by iwalpola** [comment]
Its a hardware setting (see page 26 of datasheet: https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf)
I will see if those pins are accessible on the module.

**Comment by iwalpola** [comment]
Okay, I checked how to change it. Can you see two labels "R1" and "R2" on your circuit board? You have to move the resistor from the R1 position to the R2 position.
![r1r2](https://user-images.githubusercontent.com/10414780/29279438-6aecbeb8-8135-11e7-92b9-ddeecf7425e0.png)

http://www.thebackshed.com/forum/forum_posts.asp?TID=8435

**Comment by shaddow501** [comment]
I have this module, I don’t think I can access those pins…

 

https://www.aliexpress.com/item/3-2-inch-TFT-LCD-Touch-Screen-Module-Display-Ultra-HD-320X240-ILI9341-for-3-2/32808968215.html?spm=2114.search0104.3.18.MZjrms&ws_ab_test=searchweb0_0,searchweb201602_2_10152_10065_10151_10068_5430020_10307_10137_10060_10155_10154_5370011_10056_10055_10054_10059_100031_10099_5400020_5410011_10103_10102_10052_10053_10142_10107_10050_10051_10172_5380020_10084_10083_10080_10082_10081_10110_10111_10112_5390011_10113_10114_10312_10313_10314_10315_10316_10078_10079_10073_5420011,searchweb201603_1,ppcSwitch_5&btsid=9473434d-663c-41e9-ac4b-d660c76479c5&algo_expid=48af4fce-c6ba-4359-9a77-35c3438d458a-2&algo_pvid=48af4fce-c6ba-4359-9a77-35c3438d458a

**Comment by shaddow501** [comment]
I will try to move and see how it goes on the other type of screen.

**Comment by iwalpola** [comment]
for the aliexpress link module, try contacting the seller and ask how to switch to 8 bit parallel. They will tell you which resistor to move.

**Comment by shaddow501** [comment]
Lol I did but they do not know...

Ilan B. (Mobile)

-----Original Message-----

**Comment by shaddow501** [comment]
Yes, you are right changed the R1 to R2 and all seems to work good.

Thanks

**Comment by shaddow501** [comment]
By the way just for others to know.

After moved the resistor 0 ohm from R1 to R2 also had to connect to the 8 Bit bus by using D8 to D15 and not D0 to D7. 

Before I did this change  (R1 to R2) D8 to D15 were part of the 16 bit so it didn’t work.

**Comment by shaddow501** [comment]
Dear Sir

 

I have managed to work with the screen thank you for that, but I think something in the library is not performing well.

It seems that the library (even when it set to - #define TFT_DATA_LOW_NIBBLE  1)  does affect all GPIOA ports,  I use PA14, PA15 to control relays and I see that with no action at all sometimes they change to HIGH mode and cannot be changed to LOW even when I run command digitalWrite(PA14,LOW) they do stay on high mode (I don’t have anything else in my code that address those pins but the relay switch code).

If I change the pins from PA to PB (pins) or PC (pins) everything works well.

 

I don’t know what to look in your library that can affect those pins…

This Is a part from the H file.

 

#define TFT_DATA_PORT GPIOA

// Port data bits D0..D7:

// enable only one from below lines corresponding to your HW setup:

#define TFT_DATA_LOW_NIBBLE             1 // take the lower 8 bits: 0..7

//#define TFT_DATA_HIGH_NIBBLE        1 // take the higher 8 bits: 8..15

 

//Control pins |RD |WR |RS |CS |RST|

#define TFT_CNTRL_PORT           GPIOB

#define TFT_RD                                                PB4

#define TFT_WR                                              PB5

#define TFT_RS                                PB10

#define TFT_CS                                PB11

#define TFT_RST                                              PB3 //PB0

 

#define TFT_RD_MASK                 BIT4 // digitalPinToBitMask(TFT_RD) // 

#define TFT_WR_MASK                               BIT5 // digitalPinToBitMask(TFT_WR) // 

#define TFT_RS_MASK                 BIT10 // digitalPinToBitMask(TFT_RS) // 

#define TFT_CS_MASK                 BIT11 // digitalPinToBitMask(TFT_CS) // 

 

#if 0

                // use old definition, standard bit toggling, low speed

                #define RD_ACTIVE    digitalWrite(TFT_RD, LOW)

                #define RD_IDLE      digitalWrite(TFT_RD, HIGH)

                #define WR_ACTIVE    digitalWrite(TFT_WR, LOW)

                #define WR_IDLE      digitalWrite(TFT_WR, HIGH)

                #define CD_COMMAND   digitalWrite(TFT_RS, LOW)

                #define CD_DATA      digitalWrite(TFT_RS, HIGH)

                #define CS_ACTIVE    digitalWrite(TFT_CS, LOW)

                #define CS_IDLE      digitalWrite(TFT_CS, HIGH)

                #define CS_ACTIVE_CD_COMMAND      { CS_ACTIVE; CD_COMMAND; }

#else

                // use fast bit toggling, very fast speed!

extern gpio_reg_map * cntrlRegs;

                #define RD_ACTIVE                                                        { cntrlRegs->BRR  = TFT_RD_MASK; }

                #define RD_IDLE                                                                              { cntrlRegs->BSRR = TFT_RD_MASK; }

                #define WR_ACTIVE                                                       { cntrlRegs->BRR  = TFT_WR_MASK; }

                #define WR_IDLE                                                                             { cntrlRegs->BSRR = TFT_WR_MASK; }

                #define CD_COMMAND                                                               { cntrlRegs->BRR  = TFT_RS_MASK; }

                #define CD_DATA                                                                           { cntrlRegs->BSRR = TFT_RS_MASK; }

                #define CS_ACTIVE                                                         { cntrlRegs->BRR  = TFT_CS_MASK; }

                #define CS_IDLE                                                                               { cntrlRegs->BSRR = TFT_CS_MASK; }

                #define CS_ACTIVE_CD_COMMAND      { cntrlRegs->BRR  = (TFT_CS_MASK|TFT_RS_MASK); }

#endif

 

#define WR_STROBE { WR_ACTIVE; WR_IDLE; }

 

extern uint8_t read8_(void);

#define read8(x) ( x = read8_() )

 

extern gpio_reg_map * dataRegs;

 

#if defined(TFT_DATA_LOW_NIBBLE)

  //#warning "Using lower data nibble..."

                // set the pins to input mode

                #define setReadDir() ( dataRegs->CRL = 0x88888888 )     // set the lower 8 bits as input

//            #define setReadDir() ( dataRegs->CRL = 0x44444444 )     // set the lower 8 bits as input floating

                // set the pins to output mode

                #define setWriteDir() ( dataRegs->CRL = 0x33333333 )    // set the lower 8 bits as output

                #define TFT_DATA_SHIFT 0

#elif defined(TFT_DATA_HIGH_NIBBLE)

  #warning "Using high data nibble..."

                // set the pins to input mode

                #define setReadDir() ( dataRegs->CRH = 0x88888888 )    // set the upper 8 bits as input

                // set the pins to output mode

                #define setWriteDir() ( dataRegs->CRH = 0x33333333 )   // set the lower 8 bits as output

                #define TFT_DATA_SHIFT 8

#endif

 

// set pins to output the 8 bit value

#if 0 // slow write

#define write8(c) { Serial.print(" write8: "); Serial.print(c,HEX); Serial.write(','); \

                                                                                digitalWrite(PA0, (c&BIT0)?HIGH:LOW); \

                                                                                digitalWrite(PA1, (c&BIT1)?HIGH:LOW); \

                                                                                digitalWrite(PA2, (c&BIT2)?HIGH:LOW); \

                                                                                digitalWrite(PA3, (c&BIT3)?HIGH:LOW); \

                                                                                digitalWrite(PA4, (c&BIT4)?HIGH:LOW); \

                                                                                digitalWrite(PA5, (c&BIT5)?HIGH:LOW); \

                                                                                digitalWrite(PA6, (c&BIT6)?HIGH:LOW); \

                                                                                digitalWrite(PA7, (c&BIT7)?HIGH:LOW); \

                                                                                WR_STROBE; }

#else

#define write8(c) { uint32_t val = (((c^0x00FF)<<16) | c)<<TFT_DATA_SHIFT; \

                                                                                /*Serial.print(" write8: "); Serial.print(val,HEX); Serial.write(',');*/ \

                                                                                dataRegs->BSRR = val; WR_STROBE; }

#endif

**Comment by iwalpola** [comment]
Hi shadow, for the GPIO problem, please open a new issue on this repo.
